development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: sherman-old
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: gensherman_test_old
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock


production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: gensherman_production_old
  pool: 5
  username: root
  password: password
  socket: /var/run/mysqld/mysqld.sock